Bulk update in may 23'rd
 - Re-sync ftpsync script from see http://lists.debian.org/debian-mirrors-announce/2013/05/msg00000.html
 - change source rsync for several pkgs since mirror.unej.ac.id have a lot of problem
 - add webalizer for rsync and ftp
 - delete unused files
 - add missing files from git

Signed-off-by: FTP Master <ftpmaster@buaya.klas.or.id>

diff --git a/bin/ftpsync b/bin/ftpsync
--- a/bin/ftpsync
+++ b/bin/ftpsync
@@ -36,7 +36,7 @@ BASEDIR=${BASEDIR:-"${HOME}"}
 # Script version. DO NOT CHANGE, *unless* you change the master copy maintained
 # by Joerg Jaspert and the Debian mirroradm group.
 # This is used to track which mirror is using which script version.
-VERSION="20120521"
+VERSION="20130501"
 
 # Source our common functions
 . "${BASEDIR}/etc/common"
@@ -268,6 +268,10 @@ LOGROTATE=${LOGROTATE:-14}
 LOCK=${LOCK:-"${TO}/Archive-Update-in-Progress-${MIRRORNAME}"}
 # timeout for the lockfile, in case we have bash older than v4 (and no /proc)
 LOCKTIMEOUT=${LOCKTIMEOUT:-3600}
+# sleeping time when an AUIP file is found but is not ours
+UIPSLEEP=${UIPSLEEP:-1200}
+# retries whenever an upstream (or possibly stale) AUIP file is found
+UIPRETRIES=${UIPRETRIES:-3}
 # Do we need another rsync run?
 UPDATEREQUIRED="${TO}/Archive-Update-Required-${MIRRORNAME}"
 # Trace file for mirror stats and checks (make sure we get full hostname)
@@ -290,12 +294,23 @@ RSYNC=${RSYNC:-rsync}
 RSYNC_FILTER=${RSYNC_FILTER:-"--filter=protect_Archive-Update-in-Progress-${MIRRORNAME} --filter=protect_${TRACE} --filter=protect_Archive-Update-Required-${MIRRORNAME}"}
 # limit I/O bandwidth. Value is KBytes per second, unset or 0 is unlimited
 RSYNC_BW=${RSYNC_BW:-0}
+RSYNC_PROTOCOL=$(rsync_protocol)
+
+# Set the delete method to --delete-delay if protocol version is 30 or
+# greater (meaning rsync 3.0.0 or greater is used). Use --delete-after
+# otherwise.
+if [ 30 -le $RSYNC_PROTOCOL ]; then
+    RSYNC_DELETE_METHOD=delay
+else
+    RSYNC_DELETE_METHOD=after
+fi
+
 # Default rsync options for *every* rsync call
 RSYNC_OPTIONS=${RSYNC_OPTIONS:-"-prltvHSB8192 --timeout 3600 --stats ${RSYNC_FILTER}"}
 # Options we only use in the first pass, where we do not want packages/sources to fly in yet and don't want to delete files
-RSYNC_OPTIONS1=${RSYNC_OPTIONS1:-"--exclude Packages* --exclude Sources* --exclude Release* --exclude InRelease --exclude i18n/* --exclude ls-lR*"}
+RSYNC_OPTIONS1=${RSYNC_OPTIONS1:-"--exclude=Packages* --exclude=Sources* --exclude=Release* --exclude=InRelease --exclude=i18n/* --exclude=ls-lR*"}
 # Options for the second pass, where we do want everything, including deletion of old and now unused files
-RSYNC_OPTIONS2=${RSYNC_OPTIONS2:-"--max-delete=40000 --delay-updates --delete --delete-after --delete-excluded"}
+RSYNC_OPTIONS2=${RSYNC_OPTIONS2:-"--max-delete=40000 --delay-updates --delete --delete-excluded"}
 # Which rsync share to use on our upstream mirror?
 RSYNC_PATH=${RSYNC_PATH:-"debian"}
 
@@ -306,6 +321,11 @@ RSYNC_EXTRA=${RSYNC_EXTRA:-""}
 # Now add the bwlimit option. As default is 0 we always add it, rsync interprets
 # 0 as unlimited, so this is safe.
 RSYNC_OPTIONS="${RSYNC_EXTRA} --bwlimit=${RSYNC_BW} ${RSYNC_OPTIONS}"
+
+# Finally, make sure RSYNC_OPTIONS2 has either --delete-after or --deleter-delay
+if ! [[ ${RSYNC_OPTIONS2} =~ --delete-(after|delay) ]]; then
+    RSYNC_OPTIONS2+=" --delete-${RSYNC_DELETE_METHOD}"
+fi
 
 # We have no default host to sync from, but will error out if its unset
 RSYNC_HOST=${RSYNC_HOST:-""}
@@ -342,16 +362,16 @@ EXCLUDE=${EXCLUDE:-""}
 
 # The temp directory used by rsync --delay-updates is not
 # world-readable remotely. Always exclude it to avoid errors.
-EXCLUDE="${EXCLUDE} --exclude .~tmp~/"
+EXCLUDE="${EXCLUDE} --exclude=.~tmp~/"
 
 SOURCE_EXCLUDE=${SOURCE_EXCLUDE:-""}
 ARCH_EXCLUDE=${ARCH_EXCLUDE:-""}
 # Exclude architectures defined in $ARCH_EXCLUDE
 for ARCH in ${ARCH_EXCLUDE}; do
-    EXCLUDE="${EXCLUDE} --exclude binary-${ARCH}/ --exclude installer-${ARCH}/ --exclude Contents-${ARCH}.gz --exclude Contents-udeb-${ARCH}.gz --exclude Contents-${ARCH}.diff/ --exclude arch-${ARCH}.files --exclude arch-${ARCH}.list.gz --exclude *_${ARCH}.deb --exclude *_${ARCH}.udeb --exclude *_${ARCH}.changes"
+    EXCLUDE="${EXCLUDE} --exclude=binary-${ARCH}/ --exclude=installer-${ARCH}/ --exclude=Contents-${ARCH}.gz --exclude=Contents-udeb-${ARCH}.gz --exclude=Contents-${ARCH}.diff/ --exclude=arch-${ARCH}.files --exclude=arch-${ARCH}.list.gz --exclude=*_${ARCH}.deb --exclude=*_${ARCH}.udeb --exclude=*_${ARCH}.changes"
     if [ "${ARCH}" = "source" ]; then
         if [ -z ${SOURCE_EXCLUDE} ]; then
-            SOURCE_EXCLUDE=" --exclude source/ --exclude *.tar.gz --exclude *.diff.gz --exclude *.tar.bz2 --exclude *.tar.xz -exclude *.diff.bz2 --exclude *.dsc "
+            SOURCE_EXCLUDE=" --exclude=source/ --exclude=*.tar.gz --exclude=*.diff.gz --exclude=*.tar.bz2 --exclude=*.tar.xz --exclude=*.diff.bz2 --exclude=*.dsc "
         fi
     fi
 done
@@ -459,6 +479,8 @@ fi
 export RSYNC_PASSWORD
 export RSYNC_PROXY
 
+UPDATE_RETRIES=0
+
 while [ -e "${UPDATEREQUIRED}" ]; do
     log "Running mirrorsync, update is required, ${UPDATEREQUIRED} exists"
 
@@ -471,7 +493,7 @@ while [ -e "${UPDATEREQUIRED}" ]; do
             set +e
             # Step one, sync everything except Packages/Releases
             ${RSYNC} ${RSYNC_OPTIONS} ${RSYNC_OPTIONS1} ${EXCLUDE} ${SOURCE_EXCLUDE} \
-                ${RSYNCPTH}::${RSYNC_PATH} "${TO}" #>"${LOGDIR}/rsync-${NAME}.log" 2>"${LOGDIR}/rsync-${NAME}.error"
+                ${RSYNCPTH}::${RSYNC_PATH} "${TO}" # >"${LOGDIR}/rsync-${NAME}.log" 2>"${LOGDIR}/rsync-${NAME}.error"
             result=$?
             set -e
 
@@ -501,17 +523,54 @@ while [ -e "${UPDATEREQUIRED}" ]; do
 
     # if we want stage2 *or* all
     if [ "xtruex" = "x${SYNCSTAGE2}x" ] || [ "xtruex" = "x${SYNCALL}x" ]; then
-        log "Running stage2: ${RSYNC} ${RSYNC_OPTIONS} ${RSYNC_OPTIONS2} ${EXCLUDE} ${SOURCE_EXCLUDE} ${RSYNCPTH}::${RSYNC_PATH} ${TO}"
+        upstream_uip=false
+        for aupfile in "${TO}/Archive-Update-in-Progress-"*; do
+            case "$aupfile" in
+                "${TO}/Archive-Update-in-Progress-*")
+                    error "Lock file is missing, this should not happen"
+                    ;;
+                "${LOCK}")
+                    :
+                    ;;
+                *)
+                    if [ -f "$aupfile" ]; then
+                        # Remove the file, it will be synced again if
+                        # upstream is still not done
+                        rm -f "$aupfile"
+                    else
+                        log "AUIP file '$aupfile' is not really a file, weird"
+                    fi
+                    upstream_uip=true
+                    ;;
+            esac
+        done
 
-        set +e
-        # We are lucky, it worked. Now do step 2 and sync again, this time including
-        # the packages/releases files
-        ${RSYNC} ${RSYNC_OPTIONS} ${RSYNC_OPTIONS2} ${EXCLUDE} ${SOURCE_EXCLUDE} \
-            ${RSYNCPTH}::${RSYNC_PATH} "${TO}" #>>"${LOGDIR}/rsync-${NAME}.log" 2>>"${LOGDIR}/rsync-${NAME}.error"
-        result=$?
-        set -e
+        if [ "xtruex" = "x${upstream_uip}x" ]; then
+            log "Upstream archive update in progress, skipping stage2"
+            if [ ${UPDATE_RETRIES} -lt ${UIPRETRIES} ]; then
+                log "Retrying update in ${UIPSLEEP}"
+                touch "${UPDATEREQUIRED}"
+                UPDATE_RETRIES=$(($UPDATE_RETRIES+1))
+                sleep "${UIPSLEEP}"
+                result=0
+            else
+                error "Update has been retried ${UPDATEREQUIRED} times, aborting"
+                log "Perhaps upstream is still updating or there's a stale AUIP file"
+                result=1
+            fi
+        else
+            log "Running stage2: ${RSYNC} ${RSYNC_OPTIONS} ${RSYNC_OPTIONS2} ${EXCLUDE} ${SOURCE_EXCLUDE} ${RSYNCPTH}::${RSYNC_PATH} ${TO}"
 
-        log "Back from rsync with returncode ${result}"
+            set +e
+            # We are lucky, it worked. Now do step 2 and sync again, this time including
+            # the packages/releases files
+            ${RSYNC} ${RSYNC_OPTIONS} ${RSYNC_OPTIONS2} ${EXCLUDE} ${SOURCE_EXCLUDE} \
+                ${RSYNCPTH}::${RSYNC_PATH} "${TO}" #>>"${LOGDIR}/rsync-${NAME}.log" 2>>"${LOGDIR}/rsync-${NAME}.error"
+            result=$?
+            set -e
+
+            log "Back from rsync with returncode ${result}"
+        fi
     else
         # Fake a good resultcode
         result=0
@@ -549,9 +608,9 @@ if [ "xtruex" = "x${SYNCSTAGE2}x" ] || [ "xtruex" = "x${SYNCALL}x" ]; then
         terse|full)
             log "Creating a ${EXTENDEDTRACE} trace file"
             if [ -d "$(dirname "${TO}/${TRACE}")" ]; then
-                LC_ALL=POSIX LANG=POSIX date -u > "${TO}/${TRACE}"
-                echo "Used ftpsync version: ${VERSION}" >> "${TO}/${TRACE}"
-                echo "Running on host: $(hostname -f)" >> "${TO}/${TRACE}"
+                LC_ALL=POSIX LANG=POSIX date -u > "${TO}/${TRACE}.new"
+                echo "Used ftpsync version: ${VERSION}" >> "${TO}/${TRACE}.new"
+                echo "Running on host: $(hostname -f)" >> "${TO}/${TRACE}.new"
                 if [ "xfullx" = "x${EXTENDEDTRACE}x" ]; then
                     GLOBALARCHLIST="source amd64 armel armhf hurd-i386 i386 ia64 kfreebsd-amd64 kfreebsd-i386 mips mipsel powerpc s390 s390x sparc"
 
@@ -563,9 +622,10 @@ if [ "xtruex" = "x${SYNCSTAGE2}x" ] || [ "xtruex" = "x${SYNCALL}x" ]; then
                         fi
                     done
                     out="GUESSED:{${ARCHLIST}}"
-                    echo "Architectures: ${out}" >> "${TO}/${TRACE}"
-                    echo "Upstream-mirror: ${RSYNC_HOST}" >> "${TO}/${TRACE}"
+                    echo "Architectures: ${out}" >> "${TO}/${TRACE}.new"
+                    echo "Upstream-mirror: ${RSYNC_HOST}" >> "${TO}/${TRACE}.new"
                 fi # full trace
+                mv "${TO}/${TRACE}.new" "${TO}/${TRACE}"
             fi
             ;;
         *)
@@ -598,7 +658,7 @@ if [ -r "${TO}/project/ftpsync/LATEST.VERSION" ]; then
         LATEST=0
     fi
     if [ ${LATEST} -gt ${VERSION} ]; then
-        if [ -z "${MAILTO}" ]; then
+        if [ -n "${MAILTO}" ]; then
             difference=0
             if [ -f "${LOGDIR}/ftpsync.newversion" ]; then
                 stamptime=$(< "${LOGDIR}/ftpsync.newversion")
